### ISSUE TITLE
CoreDNS readiness stuck waiting on Kubernetes

### ISSUE THREAD

**Issue by rtheis** [coredns/coredns#4014] opened 2020-07-20 12:37 UTC
**What happened**:

We were running a CoreDNS regression test that included reloading the config.  Only 1 of the 3 CoreDNS pods failed to return to a ready state after reloading the config.  We've run this regression test many times without any problems so this is likely timing related and may involve network flakes.  Deleting the not ready CoreDNS pod fixed the problem indicating that any network flakes no longer exist on the node.

**What you expected to happen**:

CoreDNS liveness probe detects that the CoreDNS pod needs to be restarted.

**How to reproduce it (as minimally and precisely as possible)**:

We don't have an easy recreate scenario. The problem may be triggered by master network connectivity flakes.

**Anything else we need to know?**:

Could this be related to https://github.com/coredns/coredns/issues/3860?

**Environment**:

- the version of CoreDNS: 1.6.9
- Corefile: See below
- logs, if applicable: See below
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Others: Failure seen on IBM Cloud Kubernetes Service clusters running Kubernetes version 1.18.

**Corefile:**
```
    # Add your CoreDNS customizations as import files.
    # Refer to https://cloud.ibm.com/docs/containers?topic=containers-cluster_dns for details.
    .:53 {
        errors
        health {
            lameduck 10s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

**CoreDNS pod logs:**
```
.:53
[INFO] plugin/reload: Running configuration MD5 = 1d49b41a5234f818668946c50f966f41
CoreDNS-1.6.9
linux/amd64, go1.14.1, 1766568
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 10s
[INFO] plugin/ready: Still waiting on: "kubernetes"
[ERROR] plugin/errors: 2 7908400895214155629.7887247716783733414.bar.com. HINFO: plugin/loop: no next plugin found
[INFO] plugin/reload: Running configuration MD5 = 3f4c3fd697b2b48378dbafb40d79b436
[INFO] Reloading complete
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] Reloading
[INFO] plugin/health: Going into lameduck mode for 10s
I0720 09:29:16.728254       1 trace.go:116] Trace[336122540]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2020-07-20 09:28:00.843714926 +0000 UTC m=+320.156889486) (total time: 1m15.884423404s):
Trace[336122540]: [1m15.884353924s] [1m15.884353924s] Objects listed
I0720 09:29:16.741072       1 trace.go:116] Trace[1747278511]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2020-07-20 09:28:00.843718594 +0000 UTC m=+320.156893141) (total time: 1m15.897287558s):
Trace[1747278511]: [1m15.897287558s] [1m15.897287558s] END
E0720 09:29:16.741111       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Service: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 13; INTERNAL_ERROR
I0720 09:29:16.742398       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105 (started: 2020-07-20 09:28:00.843848564 +0000 UTC m=+320.157022925) (total time: 1m15.898502193s):
Trace[460128162]: [1m15.898502193s] [1m15.898502193s] END
E0720 09:29:16.742422       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.4/tools/cache/reflector.go:105: Failed to list *v1.Endpoints: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 15; INTERNAL_ERROR
[INFO] plugin/reload: Running configuration MD5 = 1d49b41a5234f818668946c50f966f41
[INFO] Reloading complete
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
...
```

**Comment by chrisohaver** [comment] 2020-07-20 13:27
This doesn't seem related to #3860.
The client.go trace errors here are the _list_ step, before the _watch_ is established: `Failed to list *v1.Service: stream error when reading response body, may be caused by closed connection.` When ListAndWatch fails, K8's client.go client attempts to relist until successful with a backoff. 

Anyways, there are some peculiarities going on in the log, _before_ the error.  CoreDNS is reloading repeatedly (well, twice).  Is the Configmap being changed during this time?  It seems that a reload triggered the client.go error by closing the connection while it was retrieving a list.

Also there is a "no next plugin error" from loop plugin, which should not happen, since the forward plugin would have handled the loop probe ... assuming the corefile was not changed from what is in the description... however the reloads suggest the corefile _has_ changed.  Strangely, The loop plugin sent a probe into `bar.com.`, which implies that it was sent from a `bar.com.` zone, but one does not exist in the Corefile given.  This lines up with the corefile being changed during this time.

Adding timestamps to the output would help a bit to understand the timing of log events.

One possible workaround/option is to point the coredns Deployment's liveness probe at the _ready_ plugin instead of at the health plugin. In this way, a CoreDNS pod will get killed and respawned if it is unready. This is (more ore less) how things worked prior to k8s 1.16.

**Comment by rtheis** [comment] 2020-07-21 13:39
@chrisohaver We are changing the Corefile in the tests to trigger a reload.  The changes are as follows:

```
        sed -i '/^        prometheus :9153/i \        federation cluster.local {\n            foo foo.feddomain.com\n        }' "${TMP_COREDNS_CM_FILE}"
        sed -i '/^    .:53 {/i \    import MyCorefile' "${TMP_COREDNS_CM_FILE}"
        sed -i '/^  Corefile: |/i \  MyCorefile: |\n    bar.com:53 {\n        errors\n        cache 30\n        loop\n    }' "${TMP_COREDNS_CM_FILE}"
```

We then restore the Corefile to the original settings.

**Comment by chrisohaver** [comment] 2020-07-21 14:48
Ah - I missed the obvious "this is part of a reload test" in your description ...

The _loop_ error is expected, because there is no answer-providing plugin in the `bar.com` server block.

There _could_ be a bug here related to reload (there have been a few reload related bugs in the past). OTOH, the other instances didn't seem to have a problem, and the afflicted instance had the issue repeatedly.  It suggests that the pod was somehow flaked out.  Perhaps a race issue with starting the cluster and creating the pod (i don't know if the test runs in a pre-existing cluster or if the cluster is spun up on demand for the test).  Delete/reschedule could fix something of that nature, or perhaps that there are issues with pod's node, and after being deleted its replacement gets rescheduled onto a different node (don't know how many nodes are in the test env). Without timestamps it's hard to tell how quickly these events occurred.  How soon would the first reload have occur after the CoreDNS Pod started up?

Regardless of the cause, if you want kubernetes to kill/reschedule a pod in this state, then you can alter your CoreDNS Deployment to point the liveness probe at the _ready_ plugin endpoint (`/ready` on port 8081) instead of at the _health_ plugin. IOW, set up the liveness probe to kill coredns pods that fails the ready endpoint check after X period of time. The (fairly minor) reason we _dont_ do this in the default K8s CoreDNS deployment is to allow CoreDNS to serve upstream DNS to clients if the k8s API is down when CoreDNS starts up.

**Comment by rtheis** [comment] 2020-07-25 12:36
The test runs on an existing cluster.  Deleting the CoreDNS pod fixed the problem.  There was no indication of node problems.  The reloads came well after (30+ minutes) the CoreDNS pod started.

We've been running this same test a long time and this is the first time we've seen this problem.  Further, we haven't had any customer reports of this problem either.  We'll probably leave the liveness and readiness probes as-is unless this becomes a bigger problem.

Thanks for the help.

**Closed as completed** 2020-08-28 10:33 UTC
Labels: bug, kubernetes
