### ISSUE TITLE
CoreDNS 1.8.4 unable to upgrade upgrading from 1.19.11 to 1.20.7 facing the issue of CoreDNS

### ISSUE THREAD

**Issue by Chetan7272** [coredns/coredns#4851] opened 2021-09-07 15:27 UTC
we are trying to upgrade AKS cluster 1.19.11 to 1.20.7 and having error for CoreDNS 1.8.3 so need to upgrade to 1.8.4 but it still rollback to 1.8.3 in 5 min after upgrade of CoreDNS 1.8.4. As per AKS release note it suppose to roll out CoreDNS 1.8.4 on 09/02/2021 but it still not. Any lead or help would be nice because our AKS Cluster version 1.19.11 is going to out in October 2021.

**Comment by yongtang** [comment] 2021-09-07 15:30
@Chetan7272 From the description it looks like the issue is on AKS rollout side? Have you contacted Azure with respect to the issue you are facing?

**Comment by chrisohaver** [comment] 2021-09-07 16:15
A rollback after 5 minutes could be some kind of AKS add-on manager type thing, as I suggested when you asked in slack last week: https://cloud-native.slack.com/archives/C4DF7FP71/p1630013201002800.  IOW, Possibly AKS is locking down the CoreDNS deployment, and reverting it if it ever changes (checking every 5 minutes or so).

~Also, per https://github.com/Azure/AKS/releases/tag/2021-09-02, the rollout isn't complete yet...~

~> **Release 2021-09-02**~
~> This release is rolling out to all regions - **estimated time for completed roll out is 2021-09-09** for public cloud and 2021-09-18 for sovereign clouds.~

Nevermind - I was reading the wrong release note: https://github.com/Azure/AKS/releases/tag/2021-08-26.

**Comment by chrisohaver** [comment] 2021-09-07 17:15
Looks like AKS has cancelled the rollout due to the CoreDNS 1.8.4 regression in the _rewrite_ plugin.

https://github.com/Azure/AKS/issues/2521#issuecomment-911901518

FYI: The rewrite regression has been [fixed and merged](https://github.com/coredns/coredns/pull/4840), so it will be fixed in 1.8.5.

**Comment by chrisohaver** [comment] 2021-09-07 17:53
>  We are trying to upgrade AKS cluster 1.19.11 to 1.20.7 and having error for CoreDNS 1.8.3 so need to upgrade to 1.8.4

@Chetan7272, what error are you seeing with 1.8.3?

**Comment by Chetan7272** [comment] 2021-09-08 14:43
what error are you seeing with 1.8.3?
@chrisohaver  
Warning: (DNS ISSUE?) We have not started up yet, and we are not declaring ready, but our pod is showing up within the ( pod )service
Warning: (DNS ISSUE?) If you are using coredns >=1.8.1 to <=1.8.3, there is a known coredns bug which will the portal pods from starting.

**Comment by chrisohaver** [comment] 2021-09-08 14:57
@Chetan7272, Where do you see that error?

**Comment by Chetan7272** [comment] 2021-09-08 17:20
@chrisohaver, log file.

**Comment by chrisohaver** [comment] 2021-09-08 17:30
Closing since original questions are answered.

CoreDNS reverts back to prior version:  Probably due to AKS reverting it to its desired state.
AKS hasn't rolled out 1.8.4:  The 1.8.4 rollout was cancelled due to a _rewrite_ plugin regression in 1.8.4.

**Closed as completed by chrisohaver** 2021-09-08 17:30 UTC
Labels: question, needs info, kubernetes
