### ISSUE TITLE
bug: grpc + tls cause no graceful reload

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [coredns/coredns#1244] opened 2017-11-18 16:29 UTC
Observed:
```
- name: github.com/coredns/coredns
  version: c53968e5c48f8a71f8c491bd39cdda4ebe701116
- name: github.com/miekg/dns
  version: 7994cb36eaf858ccb42fe26da404c345eca1d62d
- name: github.com/mholt/caddy
  version: 1125a236eabb61bbccb5b6a1af1a48e39da59a20
```
```
grpc://.:443 {
}
```
kill -SIGUSR1 coredns_PID # no issues
```
grpc://.:443 {
	tls publickey.cer private.key publickey.cer
}
```
kill -SIGUSR1 coredns_PID
```
Output:
root@/build# ./coredns
grpc://.:443
2017/11/18 19:06:31 [INFO] CoreDNS-0.9.10
2017/11/18 19:06:31 [INFO] linux/amd64, go1.9.2, 
CoreDNS-0.9.10
linux/amd64, go1.9.2, 
2017/11/18 19:06:39 [INFO] SIGUSR1: Reloading
2017/11/18 19:06:39 [INFO] Reloading
2017/11/18 19:06:39 [ERROR] SIGUSR1: listen tcp :443: bind: address already in use
````

**Comment by miekg** [comment] 2017-11-21 11:37
Odd. With certs the grpc conn stays alive; doesn't get closed on reload, but otherwise it will?

**Comment by yuewko** [comment] 2017-11-21 13:45
It would appear that the issue is, in the case of TLS, the Listener returned by tls.Listen() does not implement the caddy.Listener interface. In this case, the underlying implementation is an (unexported) tls.listener object, which does not implement the File() method that is in the caddy.Listener contract.

Whereas, in the case of just TCP, the underlying implementation is an net.TCPListener object, which does implement the caddy.Listener interface.

I have already implemented a fix that addressed the above, and I'm able to perform a restart without the above error. I am currently trying to make sure that the restarted service does work.

**Comment by fturib** [comment] 2017-11-21 13:51
@miekg : does it make sense to assign this issue to @yuewko  ? if yes, can you assign it to him ?

**Comment by miekg** [comment] 2017-11-21 14:21
@fturib I can't, because not a member? Pretty stupid reason, let's see if there are buttons to press here.

**Comment by fturib** [comment] 2017-11-21 14:46
@miekg in that case, can you assign to me ? Ko is working here in the same office. And we will know this issue is getting addressed by someone. Thanks.

**Closed as completed** 2018-01-18 21:51 UTC
Labels: bug
