### ISSUE TITLE
How to specify custom plugin version

### ISSUE THREAD

**Issue by Sherlock-Holo** [coredns/coredns#2839] opened 2019-05-24 07:07 UTC
I write my coredns plugin and add it into plugin.cfg, however I don't find a way to specify the plugin version, does not coredns support this feature?

**Comment by miekg** [comment] 2019-05-24 15:01
Afaict only master is supported. Now with go modules we can maybe make this
smarter...

**Comment by Sherlock-Holo** [comment] 2019-05-25 03:24
plugin.cfg use format foo:foo, could we use format like foo:foo@master bar:bar@v1.2.0 or bar:bar@d13578a to specify version？

**Comment by chrisohaver** [comment] 2019-05-25 15:07
FWIW, I’ve been using the replace directive in go mod to build coredns using locally checked out unmerged PRs of external plugin repos.

On May 24, 2019, at 11:25 PM, Sherlock Holo <notifications@github.com<mailto:notifications@github.com>> wrote:


plugin.cfg use format foo:foo, could we use format like foo:foo@master bar:bar@v1.2.0 or bar:bar@d13578a to specify version？

**Comment by miekg** [comment] 2019-05-27 10:00
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] How to specif..." ]
>FWIW, I’ve been using the replace directive in go mod to build coredns using locally checked out unmerged PRs of external plugin repos.
>
>On May 24, 2019, at 11:25 PM, Sherlock Holo <notifications@github.com<mailto:notifications@github.com>> wrote:
>
>
>plugin.cfg use format foo:foo, could we use format like foo:foo@master bar:bar@v1.2.0 or bar:bar@d13578a to specify version？

We use go generate to update imports, imports in Go are not versioned. So 
indeed, this needs to be solved with some go mod hackery.

/label: question

**Comment by yongtang** [comment] 2019-05-27 13:25
There are some corner cases in go mod that may complicate. For example, I noticed that in go.sum there are actually two versions of `github.com/miekg/dns`. One is v1.1.3 and another is v1.1.8. I assume one (v1.1.3) is from the indirect dependency though I am still trying to track down on which library should update.

**Comment by yongtang** [comment] 2019-05-27 14:21
On a side note, the multiple versions of `github.com/miekg/dns` in go.sum is caused by caddy's usage of dns v1.1.2. Created a PR #2845 to address the issue.

**Comment by yongtang** [comment] 2019-05-27 14:38
Back to the topic of this issue, @Sherlock-Holo overall it should be possible to specify a custom plugin version, just need to explicitly require the version in `go.mod` (or replace in case there is duplicate).

**Comment by Sherlock-Holo** [comment] 2019-05-28 01:28
I have written 2 plugins for my DNS, every time I build a coredns it will download master dependencies but sometimes the latest commit has bugs and need to be fixed by next commit

**Comment by miekg** [comment] 2019-06-03 09:47
there is not much we can do here, the only recourse you have as what @yongtang mentioned in https://github.com/coredns/coredns/issues/2839#issuecomment-496233675.

Closing

**Closed as completed by miekg** 2019-06-03 09:47 UTC
Labels: question
