### ISSUE TITLE
plugin/auto:After auto is configured, the forward is invalid.

### ISSUE THREAD

**Issue by Futurefangyuan** [coredns/coredns#3203] opened 2019-08-26 09:47 UTC
configure：
. {
  hosts {
    fallthrough
  }
  auto {
    directory /data/coredns/zone/ (.*) {1}
  }
  forward . 8.8.8.8
  cache 10
  reload 10s
  log
  errors
}

result:
[root@bre-coredns.a1-60-45.own.unp /data/coredns/conf]dig www.google.com @127.0.0.1 +short
[root@bre-coredns.a1-60-45.own.unp /data/coredns/conf]dig free.bj01 @127.0.0.1 +short              
10.1.1.1

Forward google's dns can not resolve, but the zone can be resolved

**Comment by stp-ip** [comment] 2019-08-26 10:50
Duplicate of #3033 as far as I can see.

**Closed as completed** 2019-08-26 10:50 UTC
Labels: bug, duplicate, plugin/auto
