### ISSUE TITLE
codecov should not fail the whole build

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#752] opened 2017-06-23 22:26 UTC
Codecov is useful, but is should not fail the whole build (in github) when it fails.

@yongtang is that possible?

**Comment by yongtang** [comment] 2017-06-24 18:06
The issue is fixed in #754. Now codecov is only considered as failure if coverage is less than 40%.

**Comment by yongtang** [comment] 2017-06-27 15:40
Let me re-open it. The `codecov/project` entry has been fixed. But `codecov/patch` still need further fix.

**Closed as completed** 2017-06-27 17:12 UTC

**Comment by yongtang** [comment] 2017-06-27 17:13
#752 should be fixed by PR #758. We will only see two status report for each PR: one is the TravisCI, another is `codecov/project` from CodeCov. That should address the confusion we had before.
