### ISSUE TITLE
Answer rewrites not performed if a subsequent plugin returns RcodeServerFailure

### ISSUE THREAD

**Issue by Arachnid** [coredns/coredns#4407] opened 2021-01-18 22:36 UTC
**What happened**: When using the rewrite plugin with answer rewrites, if a subsequent plugin returns RcodeServerFailure, the rewrite plugin answer rewrites do not execute. As a result, a reply is sent with a question field whose name does not match the original query name, causing "Question section mismatch" in Dig.

**What you expected to happen**: The question section of the reply should be rewritten according to the rewrite rules, even if the response is an RcodeServerFailure.

**How to reproduce it (as minimally and precisely as possible)**: Configure CoreDNS with name and answer rewrites, and a subsequent plugin that causes RcodeServerFailure, then query via dig.

**Environment**:

- the version of CoreDNS: Commit f286a24b4e2c8027b9045b4fb36f92ecf5ed33f1

**Comment by Arachnid** [comment] 2021-02-10 20:19
The linked PR seems to be related to #4406 - I think this was closed by mistake.

**Comment by chrisohaver** [comment] 2021-02-10 20:24
I corrected the linked in the PR before it was merged ... ~but apparently github permanently remembers all linked issues even after their referenced comments are removed (annoying).~

Edit: Ah - i see - it was also mentioned in a commit message - I only fixed the mention in the PR description.

**Comment by Arachnid** [comment] 2022-01-31 02:10
This is still a real issue!

**Comment by chrisohaver** [comment] 2022-01-31 19:21
I'm thinking this might be caused by plugins that return an error to their caller without writing to the client, relying on the underlying dns server to respond with the SERVFAIL to the client on their behalf.  In this case _rewrite_ should trap this, synthesize the rewritten SERVFAIL response, send to client, and return a NOERROR to its caller (otherwise the underlying dns server will send a second answer to the client).

**Closed as completed** 2022-02-01 21:54 UTC
Labels: bug, plugin/rewrite
