### ISSUE TITLE
resolving or rewriting works only few seconds

### ISSUE THREAD

**Issue by Seb0042** [coredns/coredns#3717] opened 2020-03-02 15:33 UTC
**What happened**:
Resolution by templating or rewriting works only few seconds
**What you expected to happen**:
Resolution works everytime
**How to reproduce it (as minimally and precisely as possible)**:
I use the dnsutils pod to test the resolution.
kubectl exec -ti dnsutils -- nslookup minio-agv.my.domain
**Anything else we need to know?**:

**Environment**:
- the version of CoreDNS: docker.io/coredns/coredns:1.6.0
- Corefile: 
```yaml

.:53 {
        log
        errors
        health
        ready
        rewrite name exact minio-agv.my.domain minio.minio.svc.my-cluster
        kubernetes my-cluster in-addr.arpa ip6.arpa {
          pods insecure
          upstream /etc/resolv.conf
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          force_tcp
        }
        loop
        reload
        loadbalance
    }
````
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): 
On masters:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

On nodes:
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2191.5.0
VERSION_ID=2191.5.0
BUILD_ID=2019-09-04-0357
PRETTY_NAME="Container Linux by CoreOS 2191.5.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

- Others:

**Comment by chrisohaver** [comment] 2020-03-02 17:20
> Resolution by templating or rewriting works only few seconds 

Can you describe the issue in more detail?

**Comment by miekg** [comment] 2020-03-02 17:26
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] resolving or ..." ]
>> Resolution by templating or rewriting works only few seconds
>
>Can you describe the issue in more detail?

can you replicate outside k8s?

/Miek

--
Miek Gieben

**Comment by johnbelamaric** [comment] 2020-03-02 17:54
Yes, CoreDNS logs would be helpful. My first guesses would be:

1) Something like add-on manager is reverting your corefile to the default; or
2) you have multiple instances of CoreDNS with different config files causing inconsistent behavior

**Comment by Seb0042** [comment] 2020-03-02 17:58
> > Resolution by templating or rewriting works only few seconds
> 
> Can you describe the issue in more detail?

When I change the configmap of coredns, just before or after the reload it is OK.
By OK I mean nslookup xxx.my.domain will get an answer based on the rewrite (minio.minio.svc.my-cluster in that case).
Few seconds later, if I launch the same command again I will have an "unknown host". If I try again and again it will sometime give the address.
I tested by deleting pods and let them recreate, same issue.

**Comment by chrisohaver** [comment] 2020-03-02 18:06
I cannot reproduce this in 1.6.0. fwiw.  It's likely this is an issue with the Kubernetes environment, not specific to CoreDNS.

Try troubleshooting steps here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by miekg** [comment] 2020-03-02 18:08
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] resolving or ..." ]
>I cannot reproduce this in 1.6.0. fwiw.  It's likely this is an issue with the Kubernetes environment, not specific to CoreDNS.
>
>Try troubleshooting steps here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

/label kubernetes
/label external

**Comment by Seb0042** [comment] 2020-03-02 18:09
> I cannot reproduce this in 1.6.0. fwiw. It's likely this is an issue with the Kubernetes environment, not specific to CoreDNS.
> 
> Try troubleshooting steps here: https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Yes, I already tried this documentation. 
I'm trying to check the log at the moment, I will let you know, but I agree with you now, may be it's more "kubernetes related".

**Comment by Seb0042** [comment] 2020-03-02 18:25
I don't know if it's related but the configmap of nodelocaldns doesn't have the same configuration of the coredns one. 
Seems it is managed with addonmanager like suggested.
addonmanager.kubernetes.io/mode: EnsureExists.

**Comment by Seb0042** [comment] 2020-03-02 18:29
ok thanks for your help I pretty sure it is related to the issue https://github.com/coredns/coredns/issues/3298
I will follow there.

**Closed as completed** 2020-03-02 18:33 UTC
Labels: question, external, kubernetes
